In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [8]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
np.random.rand(5)

array([0.68033161, 0.24739053, 0.36378124, 0.65788102, 0.06603091])

In [29]:
np.random.randn(4,4)

array([[-1.08109117,  0.07812531, -1.1643595 ,  1.25071207],
       [ 2.14187613, -0.47252837, -0.61459644, -1.62918178],
       [-0.35978977,  0.01261237,  0.70146774,  1.27721092],
       [-0.60111934,  0.52963144,  1.33084987, -0.38751004]])

In [31]:
np.random.randint(1,100,10)

array([32, 70, 70, 67, 60, 46, 85, 32, 16,  7], dtype=int32)

In [33]:
arr=np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr=np.random.randint(0,50,10)

In [36]:
ranarr

array([29, 28, 36, 21, 11, 20, 40, 15,  1, 12], dtype=int32)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

np.int32(40)

In [41]:
ranarr.min()

np.int32(1)

In [43]:
ranarr

array([29, 28, 36, 21, 11, 20, 40, 15,  1, 12], dtype=int32)

In [44]:
ranarr.argmax()

np.int64(6)

In [45]:
ranarr.argmin()

np.int64(8)

In [46]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

In [55]:
arr.dtype

dtype('int64')